version: '2'
services:

  #################################################################################################################################
  ########################                     gen_node_authorization              #####################################################
  #################################################################################################################################

    gen_node_authorization:
      build: ./.
      ports:
        - "3400:3400"
      restart: always
      environment:
        - HTTP_PORT=3400
        - MONGODB_URL=mongodb://localhost:27017/auth
        - MONGODB_URL_TEST=mongodb://localhost:27017/auth
        - COLLECTION_RETURN_SIZE=12
        - REVERSE_PROXY=http://localhost
        - ELASTIC_SEARCH_URL=http://localhost:9200
        - LOG_STASH_PORT=5000
        - DEBUG=*
        - TOKEN_EXPIRATION_TIME=60d
        - SECRET=changeMeNow
        - SALT_LENGTH=8
        - USER_NAME=gennode
        - PASSWORD=changeMeNowAndQuick
      depends_on:
        - gen_node_authorization_db
    # Defining gen_node_authorization DB
    gen_node_authorization_db:
       image: mongo:latest
       restart: always
       volumes:
         - .:/data/db

  #################################################################################################################################
  #################################################################################################################################